config/routes.rb
Roadclouding::Application.routes.draw do
  get "weibos/get"
  post 'weibos/post'
  
  resources :track_events, :only => [:show, :index]
  match 'about' => 'home#about'
  match 'download' => 'home#download'
  match 'career' => 'home#career'
  match 'follow' => 'home#follow'
  match 'contact' => 'home#contact'
  match 'commerce' => 'home#commerce'
  match 'faq' => 'home#faq'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  #match 'users/auth/:provider/callback' => 'auth_services#create'
  devise_for :users, :controllers => { :sessions => "sessions", :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get '/users/profile'
    get '/users/sign_out' => 'sessions#destroy'
  end
  resources :users, :only => [:show, :index]
  resources :token_authentications, :only => [:create, :destroy]
  
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to I18n.t("Roadclouding"), root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li.nav
      = link_to(I18n.t('Logout'), destroy_user_session_path, :method=>'delete')
  - else
    %li.nav
      = link_to(I18n.t('Login'), new_user_session_path)
  - if user_signed_in?
    %li.nav
      = link_to(I18n.t('Edit account'), edit_user_registration_path)
  - else
    %li.nav
      = link_to(I18n.t('Sign up'), new_user_registration_path)
  %li.nav
    = link_to(I18n.t('Download'), download_path)
  %li.nav
    = link_to(I18n.t('Faq'), faq_path)
  %li.nav
    = link_to(I18n.t('Career'), career_path)
  %li.nav
    = link_to(I18n.t('About'), about_path)
  %li.nav#contact
    = link_to(I18n.t('Contact'), contact_path)
  %li.nav#follow
    = link_to(I18n.t('Follow'), follow_path)
  %li.nav
    = link_to(I18n.t('Commerce'), commerce_path)

/  %li
/    %br
/    %table
/      %tr
/        %td
/          = link_to(I18n.t('English'), {:locale=>'en'})
/        %td
/          = link_to(I18n.t('Chinese'), {:locale=>'zh_CN'})      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    == <meta property="wb:webmaster" content="790e8dee79827e57" />
    == <meta property="qc:admins" content="274120701562714347541676375" />    
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "路云科技" 
    == <link href="/roadclouding.png" rel="Shortcut Icon">
    == <link href="/roadclouding.png" rel="Bookmark">
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    == <!--[if lt IE 9]>
    == <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    == <![endif]-->
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
        %hr   
        %footer
          %p &copy; 粤ICP备12058183号 Luyun Information Technologies Inc. 2012
          